apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: app-pod-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: argocd-secret1
