apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
#  serviceAccountName: default    # automountServiceAccountToken: false
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: aws-access-key-id
            namespace: default
          secretAccessKeySecretRef:
            name: aws-secret
            key: aws-secret-access-key
            namespace: default 
              # serviceAccountRef:
              #    name: default
              #    namespace: default 
